# Generated by Django 5.2.1 on 2025-05-17 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='timezone',
            field=models.CharField(default=django.utils.timezone.get_current_timezone_name, max_length=50),
        ),
    ]
